appname : "test"
inputdb:
  path: "/home/mdupont/experiments/introspector/introspector/db.sqlite3"
outputdb:
  path: "/home/mdupont/experiments/gogccintro/models/test.sqlite3"
transform:
  filter: "load_recurse"
  startnode:
    fileid : 1
    nodetype : "function_decl"	
    attrs :
      - 
        field : 'name'
        subfield : "strg"
        subvalue : "key_get_conv"
    