appname : "test"
inputdb:
  path: "sqlite:/home/mdupont/experiments/introspector/introspector/db.sqlite3"
outputdb:
  path: "sqlite:/home/mdupont/experiments/gogccintro/models/test.sqlite3"
outputtest:
  path: "/home/mdupont/experiments/gogccintro/node_types/examples/funct_decl_key_get_conv_rpc_auth.json"
transform:
  filter: "load_recurse"
  loadrecurse:
    fileid : 2
    nodetype : "function_decl"	
    attrs :
      - 
        field : 'refs_name'
        subfield : "attrs_string"
        subvalue : "key_get_conv"
