appname : "test"

inputdb:
  path: "/home/mdupont/experiments/introspector/introspector/db.sqlite3"
	
outputdb:
  path: "/home/mdupont/experiments/gogccintro/models/test.sqlite3"
  
transform:
  filter: ""

