appname : "test"
inputdb:
  path: "sqlite:/home/mdupont/experiments/introspector/introspector/db.sqlite3"
outputdb:
  path: "sqlite:/home/mdupont/experiments/gogccintro/models/test.sqlite3"
transform:
  filter: "load_recurse"
  loadrecurse:
    fileid : 1
    nodetype : "function_decl"	
    attrs :
      - 
        field : 'name'
        subfield : "attrs_string"
        subvalue : "key_get_conv"
    