translatecode:
	GOPATH=/home/mdupont/gocode/ go test -v --run TestTranslate

gencode:
	GOPATH=/home/mdupont/gocode/ go test -v --run TestGenerate

gen:
	GOPATH=/home/mdupont/gocode /home/mdupont/gocode/bin/gen

gen2:
	GOPATH=/home/mdupont/gocode/ go test -v --run TestGenerateCode

t:
	GOPATH=/home/mdupont/gocode/ go test -v --run TestTUFile

t2:
	GOPATH=/home/mdupont/gocode/ go test -v 

