package ast

func CreateTable() (*Table) {
	return &Table{
//		Idents : make(map[string] *Ident),
//		Objects:make( map[string] *Object),
		ArrayTypes : make(map[string]*ArrayType),
		AssignStmts : make(map[string]*AssignStmt),
		BadDecls : make(map[string]*BadDecl),
		BadExprs : make(map[string]*BadExpr),
		BadStmts : make(map[string]*BadStmt),
		BasicLits : make(map[string]*BasicLit),
BinaryExprs : make(map[string]*BinaryExpr),
BlockStmts : make(map[string]*BlockStmt),
BranchStmts : make(map[string]*BranchStmt),
CallExprs : make(map[string]*CallExpr),
     CaseClauses : make(map[string]*CaseClause),
     ChanDirs : make(map[string]*ChanDir),
     ChanTypes : make(map[string]*ChanType),
     CommClauses : make(map[string]*CommClause),
     CommentGroups : make(map[string]*CommentGroup),
     Comments : make(map[string]*Comment),
     CompositeLits : make(map[string]*CompositeLit),
     DeclStmts : make(map[string]*DeclStmt),

     DeferStmts : make(map[string]*DeferStmt),
     Ellipsiss : make(map[string]*Ellipsis),
     EmptyStmts : make(map[string]*EmptyStmt),
     ExprStmts : make(map[string]*ExprStmt),

     FieldLists : make(map[string]*FieldList),
     Fields : make(map[string]*Field),
     Files : make(map[string]*File),
     ForStmts : make(map[string]*ForStmt),
     FuncDecls : make(map[string]*FuncDecl),
     FuncLits : make(map[string]*FuncLit),
     FuncTypes : make(map[string]*FuncType),
     GenDecls : make(map[string]*GenDecl),
     GoStmts : make(map[string]*GoStmt),
     Idents : make(map[string]*Ident),
     IfStmts : make(map[string]*IfStmt),
     ImportSpecs : make(map[string]*ImportSpec),
     IncDecStmts : make(map[string]*IncDecStmt),
     IndexExprs : make(map[string]*IndexExpr),
     InterfaceTypes : make(map[string]*InterfaceType),
     IsExporteds : make(map[string]*IsExported),
     KeyValueExprs : make(map[string]*KeyValueExpr),
     LabeledStmts : make(map[string]*LabeledStmt),
     MapTypes : make(map[string]*MapType),
     NewIdents : make(map[string]*NewIdent),
     Nodes : make(map[string]*Node),
     Packages : make(map[string]*Package),
     ParenExprs : make(map[string]*ParenExpr),
     RangeStmts : make(map[string]*RangeStmt),
     ReturnStmts : make(map[string]*ReturnStmt),
    SelectStmts : make(map[string]*SelectStmt),
    SelectorExprs : make(map[string]*SelectorExpr),
    SendStmts : make(map[string]*SendStmt),
    SliceExprs : make(map[string]*SliceExpr),

    StarExprs : make(map[string]*StarExpr),

    StructTypes : make(map[string]*StructType),
    SwitchStmts : make(map[string]*SwitchStmt),
    TypeAssertExprs : make(map[string]*TypeAssertExpr),
    TypeSpecs : make(map[string]*TypeSpec),
    TypeSwitchStmts : make(map[string]*TypeSwitchStmt),
    UnaryExprs : make(map[string]*UnaryExpr),
    ValueSpecs : make(map[string]*ValueSpec),

		// interfaces
		Stmts : make(map[string]Stmt),
		Exprs : make(map[string]Expr),
		Specs : make(map[string]Spec),
		Decls : make(map[string]Decl),
	}
}
