// Code generated by re2dfa (https://github.com/opennota/re2dfa).

package lex
import "fmt"

func main(){
	l,s := matchFunc("accs")
	fmt.Printf("accs %d %d\n",l,s )
	l,s = matchFunc("sign")
	fmt.Printf("sign %d %d\n",l,s )
	//fmt.Printf("acc2 %d %d\n", matchFunc("acc2"))
	//fmt.Printf("access %d %d\n", matchFunc("access"))
	//fmt.Printf("acc %d %d\n", matchFunc("acc"))
	//fmt.Printf("sign %d %d\n", matchFunc("sign"))
	//fmt.Printf("sign2 %d %d\n", matchFunc("sign2"))
	//fmt.Printf("sig %d %d\n", matchFunc("sig"))
}
