# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Introspector"
license = "MIT"
licenselink = "https://github.com/h4ck3rm1k3/gogccintro/docs/gcc/CallGraph/themes/Introspector/LICENSE.md"
description = "simple theme"
homepage = "https://h4ck3rm1k3.github.io/gogccintro/gcc/CallGraph/public/"
tags = []
features = []
min_version = "0.20"

[author]
  name = "James Michael DuPont"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = "https://github.com/allnightgrocery/hugo-theme-blueberry-detox"
